# Generated by Django 2.2.12 on 2020-05-01 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=30)),
                ('batch_uid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisation_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('organisation_url', models.URLField()),
                ('organisation_logo', models.ImageField(upload_to='')),
                ('organisation_color_palette', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeachersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('teacher_uid', models.CharField(max_length=30)),
                ('teacher_subject', models.CharField(max_length=30)),
                ('teacher_designation', models.CharField(max_length=30)),
                ('teacher_organisation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coachroom.Organisation')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_uid', models.CharField(max_length=30)),
                ('student_batch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coachroom.Batch')),
                ('student_organisation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coachroom.Organisation')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=30)),
                ('slot_start_time', models.TimeField()),
                ('slot_end_time', models.TimeField()),
                ('organisation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coachroom.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coachroom.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_day', models.CharField(max_length=30)),
                ('lecture_date', models.DateField()),
                ('lecture_url', models.URLField(default=None)),
                ('lecture_batch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coachroom.Batch')),
                ('lecture_organisation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coachroom.Organisation')),
                ('lecture_slot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coachroom.Slot')),
                ('lecture_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachroom.TeachersProfile')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_teachers',
            field=models.ManyToManyField(to='coachroom.TeachersProfile'),
        ),
        migrations.AddField(
            model_name='batch',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coachroom.Organisation'),
        ),
    ]
