# Generated by Django 2.2.12 on 2020-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=30)),
                ('organisation_url', models.CharField(max_length=30)),
                ('organisation_logo', models.CharField(max_length=30)),
                ('organisation_color_palette', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_uid', models.CharField(max_length=30)),
                ('student_batch', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('teacher_uid', models.CharField(max_length=30)),
                ('teacher_subject', models.CharField(max_length=30)),
                ('teacher_designation', models.CharField(max_length=30)),
            ],
        ),
    ]
