# Generated by Django 2.2.12 on 2020-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
