# Generated by Django 2.2.12 on 2020-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachroom', '0002_organisationusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_slot', models.CharField(max_length=30)),
                ('lecture_day', models.CharField(max_length=30)),
                ('lecture_teacher', models.CharField(max_length=30)),
                ('lecture_batch', models.CharField(max_length=30)),
                ('lecture_date', models.DateField()),
                ('lecture_url', models.CharField(max_length=255)),
            ],
        ),
    ]
