# Generated by Django 2.2.12 on 2020-04-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachroom', '0003_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=30)),
                ('batch_uid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=30)),
                ('slot_start_time', models.DateField()),
                ('slot_end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('tecaher_organisation', models.CharField(max_length=30)),
                ('teacher_uid', models.CharField(max_length=30)),
                ('teacher_subject', models.CharField(max_length=30)),
                ('teacher_designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='StudentsProfile',
        ),
        migrations.DeleteModel(
            name='OrganisationUsers',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_url',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_teachers',
            field=models.ManyToManyField(to='coachroom.TeachersProfile'),
        ),
    ]
