//auth constants
export const USER_LOADING = 'USER_LOADING'; 
export const USER_LOADED = 'USER_LOADED'; 
export const AUTH_ERROR = 'AUTH_ERROR'; 
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'; 
export const REGISTER_FAIL = 'REGISTER_FAIL'; 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; 
export const LOGIN_FAIL = 'LOGIN_FAIL'; 
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//organisation constants
export const ORGANISATION_LOADING  = 'ORGANISATION_LOADING';
export const ORGANISATION_LOADED  = 'ORGANISATION_LOADED';
export const ORGANISATION_LOADING_ERROR  = 'ORGANISATION_LOADING_ERROR';

